name: utp
description: uTorrent Transport Protocol (BEP0029 specification) library implemented by pure Dart.
version: 1.0.1
repository: https://github.com/eclipseglory/utp
issue_tracker : https://github.com/eclipseglory/utp/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
