name: utp
description: uTorrent Transport Protocol (BEP0029 specification) library implemented by pure Dart.
version: 1.1.0
repository: https://github.com/xhns/utp
issue_tracker: https://github.com/xhns/utp/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
